// <auto-generated />
using System;
using ClinicAdminApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClinicAdminApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ClinicAdminApp.Models.DetailResep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Harga")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("Jumlah")
                        .HasColumnType("int");

                    b.Property<Guid>("ObatId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ResepId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("ObatId");

                    b.HasIndex("ResepId");

                    b.ToTable("DetailReseps");
                });

            modelBuilder.Entity("ClinicAdminApp.Models.Dokter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("JadwalPraktek")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NamaDokter")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NoSTR")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NoTelepon")
                        .HasColumnType("longtext");

                    b.Property<string>("Spesialis")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Dokters");
                });

            modelBuilder.Entity("ClinicAdminApp.Models.Obat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Harga")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Kategori")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("KodeObat")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NamaObat")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Satuan")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Stok")
                        .HasColumnType("int");

                    b.Property<DateTime>("TanggalExpired")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Obats");
                });

            modelBuilder.Entity("ClinicAdminApp.Models.Pasien", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Alamat")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("JenisKelamin")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NamaPasien")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NoRM")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NoTelepon")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("TanggalLahir")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Pasiens");
                });

            modelBuilder.Entity("ClinicAdminApp.Models.Pembayaran", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("BiayaObat")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("BiayaPemeriksaan")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("MetodePembayaran")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NoPembayaran")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("ResepId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("TanggalPembayaran")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("TotalBayar")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("ResepId");

                    b.ToTable("Pembayarans");
                });

            modelBuilder.Entity("ClinicAdminApp.Models.Pemeriksaan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("BeratBadan")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Catatan")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Diagnosa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("PendaftaranId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("SuhuTubuh")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("TanggalPemeriksaan")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TekananDarah")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("TinggiBadan")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("PendaftaranId");

                    b.ToTable("Pemeriksaans");
                });

            modelBuilder.Entity("ClinicAdminApp.Models.Pendaftaran", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("DokterId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Keluhan")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NoPendaftaran")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("PasienId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PoliId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("TanggalBerobat")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("DokterId");

                    b.HasIndex("PasienId");

                    b.HasIndex("PoliId");

                    b.ToTable("Pendaftarans");
                });

            modelBuilder.Entity("ClinicAdminApp.Models.Poli", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Keterangan")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("KodePoli")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Lokasi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NamaPoli")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Polis");
                });

            modelBuilder.Entity("ClinicAdminApp.Models.Resep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("NomorResep")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("PemeriksaanId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("TanggalResep")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("TotalBiaya")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("PemeriksaanId");

                    b.ToTable("Reseps");
                });

            modelBuilder.Entity("ClinicAdminApp.Models.DetailResep", b =>
                {
                    b.HasOne("ClinicAdminApp.Models.Obat", "Obat")
                        .WithMany()
                        .HasForeignKey("ObatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicAdminApp.Models.Resep", "Resep")
                        .WithMany("DetailReseps")
                        .HasForeignKey("ResepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Obat");

                    b.Navigation("Resep");
                });

            modelBuilder.Entity("ClinicAdminApp.Models.Pembayaran", b =>
                {
                    b.HasOne("ClinicAdminApp.Models.Resep", "Resep")
                        .WithMany()
                        .HasForeignKey("ResepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resep");
                });

            modelBuilder.Entity("ClinicAdminApp.Models.Pemeriksaan", b =>
                {
                    b.HasOne("ClinicAdminApp.Models.Pendaftaran", "Pendaftaran")
                        .WithMany()
                        .HasForeignKey("PendaftaranId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pendaftaran");
                });

            modelBuilder.Entity("ClinicAdminApp.Models.Pendaftaran", b =>
                {
                    b.HasOne("ClinicAdminApp.Models.Dokter", "Dokter")
                        .WithMany()
                        .HasForeignKey("DokterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicAdminApp.Models.Pasien", "Pasien")
                        .WithMany()
                        .HasForeignKey("PasienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicAdminApp.Models.Poli", "Poli")
                        .WithMany()
                        .HasForeignKey("PoliId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dokter");

                    b.Navigation("Pasien");

                    b.Navigation("Poli");
                });

            modelBuilder.Entity("ClinicAdminApp.Models.Resep", b =>
                {
                    b.HasOne("ClinicAdminApp.Models.Pemeriksaan", "Pemeriksaan")
                        .WithMany()
                        .HasForeignKey("PemeriksaanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pemeriksaan");
                });

            modelBuilder.Entity("ClinicAdminApp.Models.Resep", b =>
                {
                    b.Navigation("DetailReseps");
                });
#pragma warning restore 612, 618
        }
    }
}
